# .github/workflows/build-and-deploy.yml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subproject: ['subproject1']
#        subproject: ['mainproject', 'subproject1', 'subproject2']

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.44.0

      - name: Determine changed files
        id: changes
        run: |
          git fetch origin main
          git diff --name-only origin/main HEAD > changes.txt
          if grep -q "${{ matrix.subproject }}" changes.txt; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Build ${{ matrix.subproject }}
        if: env.changes == 'true'
        run: |
          cd ${{ matrix.subproject }}
          echo "import 'lume/cli.ts'" | deno run -A -
          mkdir -p ../webroot/${{ matrix.subproject }}
          cp -r ./_site/* ../webroot/${{ matrix.subproject }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read    
    steps:
      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.44.0

      # - name: Upload to Deno Deploy
      #   uses: denoland/deployctl@v1
      #   with:
      #     project: lume-example
      #     entrypoint: server/main.ts

    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./webroot
