# .github/workflows/build-and-deploy.yml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.44.0

      - name: Run deno task lume for subproject1
        run: |
          cd subproject1
          deno task lume

      - name: Run deno task lume for subproject2
        run: |
          cd subproject2
          deno task lume

      - name: Run deno task lume for mainproject
        run: |
          cd mainproject
          deno task lume

      - name: Copy subproject1/_site/ to ./webroot/subproject1/
        run: |
          mkdir -p ./webroot/subproject1
          cp -r subproject1/_site/* ./webroot/subproject1/

      - name: Copy subproject2/_site/ to ./webroot/subproject2/
        run: |
          mkdir -p ./webroot/subproject2
          cp -r subproject2/_site/* ./webroot/subproject2/

      - name: Copy mainproject/_site/ to ./webroot/
        run: |
          mkdir -p ./webroot
          cp -r mainproject/_site/* ./webroot/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          publish_dir: ./webroot
